# Generated by Django 4.0.4 on 2022-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0015_auto_20210904_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testjobs',
            name='custom_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='testjobs',
            name='uuid',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
