# Generated by Django 4.0.4 on 2022-05-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader', '0016_alter_testjobs_custom_id_alter_testjobs_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsstorage',
            name='identity',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
